language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - "stable"

script:
  - yarn validate

after_success:
  - yarn codecov

cache:
  yarn: true
